import os

TITLE_LABEL = "#TITLE:"
SUBTITLE_LABEL = "#SUBTITLE:"
ARTIST_LABEL = "#ARTIST:"
CREDIT_LABEL = "#CREDIT:"
MUSIC_LABEL = "#MUSIC:"
BANNER_LABEL = "#BANNER:"
BACKGROUND_LABEL = "#BACKGROUND:"
JACKET_LABEL = "#JACKET:"
BGCHANGES_LABEL = "#BGCHANGES:"
MV_LABEL = "[MV]"
DEFAULT_ENCODING = "utf8"
VIDEO_FILE_EXTENSIONS = (".avi", ".mpeg", ".mpg", ".mp4")
